package io.github.shallowinggg.sqlgen.jdbc;

import io.github.shallowinggg.sqlgen.random.Randomizer;

import java.util.Map;

/**
 * The base interface that used to insert data into table.
 *
 * @author ding shimin
 * @since 1.0
 */
public interface JdbcWriter {
    /**
     * Default amount of data to insert
     */
    int DEFAULT_ROWS = 5;

    /**
     * Insert specified amount of data into the given table.
     * The data which used to insert is generated by
     * {@link io.github.shallowinggg.sqlgen.random.Randomizer}
     * that provided by default for each table columns.
     *
     * @param table the name of table which to be inserted
     * @param rows  the amount of data to insert
     */
    void insert(String table, int rows);

    /**
     * Insert specified amount of data into the given table.
     * The data which used to insert is generated by
     * {@link io.github.shallowinggg.sqlgen.random.Randomizer}
     * that provided by default and parameter {@code customColumns}
     * for each table columns.
     *
     * @param table         the name of table which to be inserted
     * @param rows          the amount of data to insert
     * @param customColumns custom randomizer for columns
     */
    void insert(String table, int rows, Map<String, Randomizer<?>> customColumns);

    /**
     * Insert data into the given table. The data which
     * used to insert is generated by
     * {@link io.github.shallowinggg.sqlgen.random.Randomizer}
     * for each table columns. And the amount of data is
     * {@link #DEFAULT_ROWS} by default. If you want to customize
     * this value, you can invoke {@link #insert(String, int)}
     * instead of this method.
     *
     * @param table the name of table which to be inserted
     * @see #insert(String, int)
     */
    default void insert(String table) {
        insert(table, DEFAULT_ROWS);
    }
}
